// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUZTIl4AiSG0bDoJl31IIdQdS4M5OyFnY',
    appId: '1:228150015768:web:a0377fe7ced144d892106d',
    messagingSenderId: '228150015768',
    projectId: 'pucpenguin',
    authDomain: 'pucpenguin.firebaseapp.com',
    storageBucket: 'pucpenguin.firebasestorage.app',
    measurementId: 'G-SVLBK8BG3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfCLjZNWN9yneOvTUsuIoBmZ0q6O3-oOc',
    appId: '1:228150015768:android:066302e02afccb8192106d',
    messagingSenderId: '228150015768',
    projectId: 'pucpenguin',
    storageBucket: 'pucpenguin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKIZHiJNQHWMPnUiW4eI-Lk_dNbtGCTFw',
    appId: '1:228150015768:ios:9619edca7f494e3c92106d',
    messagingSenderId: '228150015768',
    projectId: 'pucpenguin',
    storageBucket: 'pucpenguin.firebasestorage.app',
    iosBundleId: 'com.example.pucPenguin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKIZHiJNQHWMPnUiW4eI-Lk_dNbtGCTFw',
    appId: '1:228150015768:ios:9619edca7f494e3c92106d',
    messagingSenderId: '228150015768',
    projectId: 'pucpenguin',
    storageBucket: 'pucpenguin.firebasestorage.app',
    iosBundleId: 'com.example.pucPenguin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUZTIl4AiSG0bDoJl31IIdQdS4M5OyFnY',
    appId: '1:228150015768:web:d36e6e96e4ebd34192106d',
    messagingSenderId: '228150015768',
    projectId: 'pucpenguin',
    authDomain: 'pucpenguin.firebaseapp.com',
    storageBucket: 'pucpenguin.firebasestorage.app',
    measurementId: 'G-T4Z0TTM34L',
  );
}
