name: puc_penguin
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
  - assets/logo.png
  - assets/icon/icon.png